name: Tag and build

on:
  push:

jobs:
  Tagging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        append_to_pre_release_tag: ''
        default_bump: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Write changelog"
      run: |
        CHANGELOG=""
        if [ -e CHANGELOG.md ]
        then
            CHANGELOG=$(cat CHANGELOG.md)
        fi
        echo -e "${{steps.tag_version.outputs.changelog}}\n\n${CHANGELOG}" > CHANGELOG.md

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: npm run webpack
    - run: npm run babel
    - name: New release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: 'dist/person-entity-card-bundle.js'
        body: ${{ steps.tag_version.outputs.changelog }}
        commit: 'main'
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        owner: 'GuyKh'
        repo: 'person-entity-card'
        tag: ${{ steps.tag_version.outputs.new_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}


